package com.tcl.launcher.json.entry;

import java.io.Serializable;
import java.util.List;

public class TvPlay implements Serializable
{
	/**
	 * 电视剧详细信息类
	 */
	private static final long serialVersionUID = 1L;
	/**
	 * This field was generated by THB Generator. This field corresponds to the
	 * database column tvplay.tvplay_id Remark - *NO SETTING* DBType - INTEGER
	 * 
	 * @mbggenerated Fri Mar 07 14:34:37 CST 2014
	 */
	private String tvplayId;
	/**
	 * This field was generated by THB Generator. This field corresponds to the
	 * database column tvplay.cn_Title Remark - 中文名称 DBType - VARCHAR
	 * 
	 * @mbggenerated Fri Mar 07 14:34:37 CST 2014
	 */
	private String cnTitle;
	/**
	 * This field was generated by THB Generator. This field corresponds to the
	 * database column tvplay.en_Title Remark - 英文名称 DBType - VARCHAR
	 * 
	 * @mbggenerated Fri Mar 07 14:34:37 CST 2014
	 */
	private String enTitle;
	/**
	 * This field was generated by THB Generator. This field corresponds to the
	 * database column tvplay.directors Remark - 导演 DBType - VARCHAR
	 * 
	 * @mbggenerated Fri Mar 07 14:34:37 CST 2014
	 */
	private String directors;
	/**
	 * This field was generated by THB Generator. This field corresponds to the
	 * database column tvplay.screenwriter Remark - 编剧 DBType - VARCHAR
	 * 
	 * @mbggenerated Fri Mar 07 14:34:37 CST 2014
	 */
	private String screenwriter;
	/**
	 * This field was generated by THB Generator. This field corresponds to the
	 * database column tvplay.actors Remark - 演员 DBType - VARCHAR
	 * 
	 * @mbggenerated Fri Mar 07 14:34:37 CST 2014
	 */
	private String actors;
	/**
	 * This field was generated by THB Generator. This field corresponds to the
	 * database column tvplay.types Remark - 类型 DBType - VARCHAR
	 * 
	 * @mbggenerated Fri Mar 07 14:34:37 CST 2014
	 */
	private String types;
	/**
	 * This field was generated by THB Generator. This field corresponds to the
	 * database column tvplay.season Remark - 第几集 DBType - VARCHAR
	 * 
	 * @mbggenerated Fri Mar 07 14:34:37 CST 2014
	 */
	private String season;
	/**
	 * This field was generated by THB Generator. This field corresponds to the
	 * database column tvplay.season_num Remark - 总共季数 DBType - VARCHAR
	 * 
	 * @mbggenerated Fri Mar 07 14:34:37 CST 2014
	 */
	private String seasonNum;
	/**
	 * This field was generated by THB Generator. This field corresponds to the
	 * database column tvplay.season_type Remark - *NO SETTING* DBType - VARCHAR
	 * 
	 * @mbggenerated Fri Mar 07 14:34:37 CST 2014
	 */
	private String seasonType;
	/**
	 * This field was generated by THB Generator. This field corresponds to the
	 * database column tvplay.tags Remark - *NO SETTING* DBType - VARCHAR
	 * 
	 * @mbggenerated Fri Mar 07 14:34:37 CST 2014
	 */
	private String tags;
	/**
	 * This field was generated by THB Generator. This field corresponds to the
	 * database column tvplay.language Remark - 语言 DBType - VARCHAR
	 * 
	 * @mbggenerated Fri Mar 07 14:34:37 CST 2014
	 */
	private String language;
	/**
	 * This field was generated by THB Generator. This field corresponds to the
	 * database column tvplay.releaseDate Remark - 发行日期 DBType - VARCHAR
	 * 
	 * @mbggenerated Fri Mar 07 14:34:37 CST 2014
	 */
	private String releasedate;
	/**
	 * This field was generated by THB Generator. This field corresponds to the
	 * database column tvplay.renames Remark - 别名 DBType - VARCHAR
	 * 
	 * @mbggenerated Fri Mar 07 14:34:37 CST 2014
	 */

	private String renames;
	/**
	 * This field was generated by THB Generator. This field corresponds to the
	 * database column tvplay.intro Remark - 简述 DBType - VARCHAR
	 * 
	 * @mbggenerated Fri Mar 07 14:34:37 CST 2014
	 */
	private String intro;
	/**
	 * This field was generated by THB Generator. This field corresponds to the
	 * database column tvplay.url Remark - 对应baidu页面url DBType - VARCHAR
	 * 
	 * @mbggenerated Fri Mar 07 14:34:37 CST 2014
	 */
	private String url;
	/**
	 * This field was generated by THB Generator. This field corresponds to the
	 * database column tvplay.cn_sub_title Remark - *NO SETTING* DBType -
	 * VARCHAR
	 * 
	 * @mbggenerated Fri Mar 07 14:34:37 CST 2014
	 */
	private String cnSubTitle;
	/**
	 * This field was generated by THB Generator. This field corresponds to the
	 * database column tvplay.rating Remark - 评分 DBType - VARCHAR
	 * 
	 * @mbggenerated Fri Mar 07 14:34:37 CST 2014
	 */
	private String rating;
	/**
	 * This field was generated by THB Generator. This field corresponds to the
	 * database column tvplay.hot Remark - 热度 DBType - VARCHAR
	 * 
	 * @mbggenerated Fri Mar 07 14:34:37 CST 2014
	 */
	private String hot;
	/**
	 * This field was generated by THB Generator. This field corresponds to the
	 * database column tvplay.en_sub_title Remark - *NO SETTING* DBType -
	 * VARCHAR
	 * 
	 * @mbggenerated Fri Mar 07 14:34:37 CST 2014
	 */
	private String enSubTitle;
	/**
	 * This field was generated by THB Generator. This field corresponds to the
	 * database column tvplay.imgh_url Remark - *NO SETTING* DBType - VARCHAR
	 * 
	 * @mbggenerated Fri Mar 07 14:34:37 CST 2014
	 */
	private String imghUrl;
	/**
	 * This field was generated by THB Generator. This field corresponds to the
	 * database column tvplay.imgv_url Remark - *NO SETTING* DBType - VARCHAR
	 * 
	 * @mbggenerated Fri Mar 07 14:34:37 CST 2014
	 */
	private String imgvUrl;
	/**
	 * This field was generated by THB Generator. This field corresponds to the
	 * database column tvplay.s_intro Remark - *NO SETTING* DBType - VARCHAR
	 * 
	 * @mbggenerated Fri Mar 07 14:34:37 CST 2014
	 */
	private String sIntro;
	/**
	 * This field was generated by THB Generator. This field corresponds to the
	 * database column tvplay.source_tvplay_id Remark - 百度id DBType - VARCHAR
	 * 
	 * @mbggenerated Fri Mar 07 14:34:37 CST 2014
	 */
	private String sourceTvplayId;
	/**
	 * This field was generated by THB Generator. This field corresponds to the
	 * database column tvplay.finish Remark - 是否完成，1完成0未完成 DBType - VARCHAR
	 * 
	 * @mbggenerated Fri Mar 07 14:34:37 CST 2014
	 */
	private String finish;
	/**
	 * This field was generated by THB Generator. This field corresponds to the
	 * database column tvplay.update Remark - 更新状态 DBType - VARCHAR
	 * 
	 * @mbggenerated Fri Mar 07 14:34:37 CST 2014
	 */
	private String updateStatus;
	/**
	 * This field was generated by THB Generator. This field corresponds to the
	 * database column tvplay.areas Remark - 区域 DBType - VARCHAR
	 * 
	 * @mbggenerated Fri Mar 07 14:34:37 CST 2014
	 */
	private String areas;
	/**
	 * This field was generated by THB Generator. This field corresponds to the
	 * database column tvplay.max_episode Remark - *NO SETTING* DBType - VARCHAR
	 * 
	 * @mbggenerated Fri Mar 07 14:34:37 CST 2014
	 */
	private String maxEpisode;
	/**
	 * This field was generated by THB Generator. This field corresponds to the
	 * database column tvplay.cur_episode Remark - *NO SETTING* DBType - VARCHAR
	 * 
	 * @mbggenerated Fri Mar 07 14:34:37 CST 2014
	 */
	private String curEpisode;
	/**
	 * This field was generated by THB Generator. This field corresponds to the
	 * database column tvplay.sites Remark - *NO SETTING* DBType - VARCHAR
	 * 
	 * @mbggenerated Fri Mar 07 14:34:37 CST 2014
	 */
	private String sites;

	private List<VodBrief> recommends;

	private List<Episode> episodes;

	public List<Episode> getEpisodes()
	{
		return episodes;
	}

	public void setEpisodes(List<Episode> episodes)
	{
		this.episodes = episodes;
	}

	public List<VodBrief> getRecommends()
	{
		return recommends;
	}


	public void setRecommends(List<VodBrief> recommends)
	{
		this.recommends = recommends;
	}

	// public List<EpisodeInfoDTO> getEpisodeInfo() {
	// return episodeInfo;
	// }
	//
	// public void setEpisodeInfo(List<EpisodeInfoDTO> episodeInfo) {
	// this.episodeInfo = episodeInfo;
	// }

	public TvPlay()
	{
		super();
	}

	public String getTvplayId()
	{
		return tvplayId;
	}

	public void setTvplayId(String tvplayId)
	{
		this.tvplayId = tvplayId;
	}

	public String getCnTitle()
	{
		return cnTitle;
	}

	public void setCnTitle(String cnTitle)
	{
		this.cnTitle = cnTitle == null ? null : cnTitle.trim();
	}

	public String getEnTitle()
	{
		return enTitle;
	}

	public void setEnTitle(String enTitle)
	{
		this.enTitle = enTitle == null ? null : enTitle.trim();
	}

	public String getDirectors()
	{
		return directors;
	}

	public void setDirectors(String directors)
	{
		this.directors = directors == null ? null : directors.trim();
	}

	public String getScreenwriter()
	{
		return screenwriter;
	}

	public void setScreenwriter(String screenwriter)
	{
		this.screenwriter = screenwriter == null ? null : screenwriter.trim();
	}

	public String getActors()
	{
		return actors;
	}

	public void setActors(String actors)
	{
		this.actors = actors == null ? null : actors.trim();
	}

	public String getTypes()
	{
		return types;
	}

	public void setTypes(String types)
	{
		this.types = types == null ? null : types.trim();
	}

	public String getSeason()
	{
		return season;
	}

	public void setSeason(String season)
	{
		this.season = season == null ? null : season.trim();
	}

	public String getSeasonNum()
	{
		return seasonNum;
	}

	public void setSeasonNum(String seasonNum)
	{
		this.seasonNum = seasonNum == null ? null : seasonNum.trim();
	}

	public String getSeasonType()
	{
		return seasonType;
	}

	public void setSeasonType(String seasonType)
	{
		this.seasonType = seasonType == null ? null : seasonType.trim();
	}

	public String getTags()
	{
		return tags;
	}

	public void setTags(String tags)
	{
		this.tags = tags == null ? null : tags.trim();
	}

	public String getLanguage()
	{
		return language;
	}

	public void setLanguage(String language)
	{
		this.language = language == null ? null : language.trim();
	}

	public String getReleasedate()
	{
		return releasedate;
	}

	public void setReleasedate(String releasedate)
	{
		this.releasedate = releasedate == null ? null : releasedate.trim();
	}

	public String getRenames()
	{
		return renames;
	}

	public void setRenames(String renames)
	{
		this.renames = renames == null ? null : renames.trim();
	}

	public String getIntro()
	{
		return intro;
	}

	public void setIntro(String intro)
	{
		this.intro = intro == null ? null : intro.trim();
	}

	public String getUrl()
	{
		return url;
	}

	public void setUrl(String url)
	{
		this.url = url == null ? null : url.trim();
	}

	public String getCnSubTitle()
	{
		return cnSubTitle;
	}

	public void setCnSubTitle(String cnSubTitle)
	{
		this.cnSubTitle = cnSubTitle == null ? null : cnSubTitle.trim();
	}

	public String getRating()
	{
		return rating;
	}

	public void setRating(String rating)
	{
		this.rating = rating == null ? null : rating.trim();
	}

	public String getHot()
	{
		return hot;
	}

	public void setHot(String hot)
	{
		this.hot = hot == null ? null : hot.trim();
	}

	public String getEnSubTitle()
	{
		return enSubTitle;
	}

	public void setEnSubTitle(String enSubTitle)
	{
		this.enSubTitle = enSubTitle == null ? null : enSubTitle.trim();
	}

	public String getImghUrl()
	{
		return imghUrl;
	}

	public void setImghUrl(String imghUrl)
	{
		this.imghUrl = imghUrl == null ? null : imghUrl.trim();
	}

	public String getImgvUrl()
	{
		return imgvUrl;
	}

	public void setImgvUrl(String imgvUrl)
	{
		this.imgvUrl = imgvUrl == null ? null : imgvUrl.trim();
	}

	public String getsIntro()
	{
		return sIntro;
	}

	public void setsIntro(String sIntro)
	{
		this.sIntro = sIntro == null ? null : sIntro.trim();
	}

	public String getSourceTvplayId()
	{
		return sourceTvplayId;
	}

	public void setSourceTvplayId(String sourceTvplayId)
	{
		this.sourceTvplayId = sourceTvplayId == null ? null : sourceTvplayId.trim();
	}

	public String getFinish()
	{
		return finish;
	}

	public void setFinish(String finish)
	{
		this.finish = finish == null ? null : finish.trim();
	}

	public String getUpdateStatus()
	{
		return updateStatus;
	}

	public void setUpdateStatus(String updateStatus)
	{
		this.updateStatus = updateStatus;
	}

	public String getAreas()
	{
		return areas;
	}

	public void setAreas(String areas)
	{
		this.areas = areas == null ? null : areas.trim();
	}

	public String getMaxEpisode()
	{
		return maxEpisode;
	}

	public void setMaxEpisode(String maxEpisode)
	{
		this.maxEpisode = maxEpisode == null ? null : maxEpisode.trim();
	}

	public String getCurEpisode()
	{
		return curEpisode;
	}

	public void setCurEpisode(String curEpisode)
	{
		this.curEpisode = curEpisode == null ? null : curEpisode.trim();
	}

	public String getSites()
	{
		return sites;
	}

	public void setSites(String sites)
	{
		this.sites = sites == null ? null : sites.trim();
	}

}